# Generated by Django 2.1.5 on 2021-05-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_auto_20210514_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
