# Generated by Django 2.1.5 on 2021-05-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0006_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=10),
        ),
    ]
