# Generated by Django 2.1.5 on 2021-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0009_auto_20210524_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='conatct_no',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=10),
        ),
    ]
