# Generated by Django 2.1.5 on 2021-05-26 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0011_auto_20210526_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
